### ISSUE TITLE
Consonância com Portaria 418/2020

### ISSUE THREAD

**Issue by edusantana** [edusantana/saber-pb#10]
Implementar Consonância com Portaria 418/2020

[ARQUITETURA AVALIATIVA OK.pdf](https://github.com/edusantana/saber-pb/files/5043094/ARQUITETURA.AVALIATIVA.OK.pdf)

**Comment by MikaelyAraujo** [comment]
Grata

Em sex, 7 de ago de 2020 15:41, Eduardo de Santana Medeiros <
notifications@github.com> escreveu:
