### ISSUE TITLE
Atualizações do Saber 2021

### ISSUE THREAD

**Issue by alissonsilvaprofessorpb** [edusantana/saber-pb#16]
Bom dia!

Sou Alisson Pereira, professore da rede Pública de Ensino do Estado da Paraíba. Gostaria de saber se a ferramenta de registros em paralelo vai ser atualizada para o ano de 2021, pois quando eu tentei fazer o registro de aulas em paralelo esse ano eu não conseguia ver as minhas turmas de 2021 (só aparecia as turmas do ano passado).

Gostaria de saber se haverá alguma atualização em relação a essa ferramenta de registro.

Respeitosamente,

Alisson Pereira.

Segue em anexo a imagem com a tela de cadastro de aulas apenas com as turmas do ano passado.

![image](https://user-images.githubusercontent.com/66706274/114724144-a5681a00-9d11-11eb-8325-77d5f297fab3.png)

**Comment by edusantana** [comment]
Olá Alisson, você precisa atualizar manualmente o conteúdo das caixas. Veja o vídeo que ensinei o cadastro em paralelo no youtube, veja a descrição do vídeo, lá tem um link para o trecho do vídeo que ensina atualizar isso aí.

**Comment by alissonsilvaprofessorpb** [comment]
Obrigado pelas orientações. Deu certo aqui! Grande abraço, amigo!
